name: CLJS Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
          bb: latest

      - name: Setup Node.js for cljs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache m2
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}

      - name: Cache gitlibs
        uses: actions/cache@v4
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}

      - name: Install dependencies
        run: npm install

      - name: ClojureScript tests
        run: bb test:cljs
        env:
          NODE_OPTIONS: --max-old-space-size=8192
