name: Release to Clojars

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Clojars Release
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Cache m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}

      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}

      - name: Install dependencies
        run: clojure -P -M:build

      - name: Release
        run: clojure -T:build publish
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_TOKEN }}
