name: Clojure CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
          bb: latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache m2
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}

      - name: Cache gitlibs
        uses: actions/cache@v4
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}

      - name: Prepare dependencies
        run: clojure -P -M:test:runner

      - name: Run Clojure tests
        run: bb test:clj
